/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MoonShotFactory } from "./MoonShotFactory";
export type { MoonShotToken } from "./MoonShotToken";
