export enum MintTokenCurveType {
  BASE_CONSTANT_PRODUCT_V1 = 'BASE_CONSTANT_PRODUCT_V1',
  ABSTRACT_CONSTANT_PRODUCT_v1 = 'ABSTRACT_CONSTANT_PRODUCT_V1',
  BERA_CONSTANT_PRODUCT_V1 = 'BERA_CONSTANT_PRODUCT_V1',
}
